# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Workflow Android App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > suitplay.keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch suitplay.keystore.asc > suitplay.keystore          
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/YkeSmit1/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}           
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build suitplay\suitplay.csproj -c Release -f net9.0-android /p:AndroidSigningKeyStore=suitplay.keystore /p:AndroidSigningKeyAlias=suitplay /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}"
    - uses: actions/upload-artifact@v4
      with:
        name: distribute_suitplay_android
        path: |
          ./**/*.aab
          ./**/*.apk
          ./**/*.keystore
